spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: password
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:tweetDbTest;MODE=MySQL;
    username: sa
    password: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          default_schema:
          dialect: org.hibernate.dialect.H2Dialect
          jdbc:
            lob:
              non_contextual_creation: true

active-mq:
  queue:
    tweet: tweets-published
twitter:
  tweets:
    terms:
      - coronavirus
      - vacaciones
      - vacances
    languages:
      - es
      - fr
      - it
    min_followers: 1500
  hashtags_num_clasification: 10

